name: Autograding Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    if: (github.event_name != 'push' || github.event.head_commit.message != 'Initial commit')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: education/autograding@v1
